name: Scaffold a new service
on:
  workflow_dispatch:
    inputs:
      port_context:
        required: true
        description: Includes the action's run id
      service_name:
        required: true
        description: The name of the new service
        type: string
      template_name:
        required: true
        description: The name of the new service
        type: string
jobs:
  run-graphql-mutation:
    runs-on: ubuntu-latest
    steps:
      - name: Send GraphQL Mutation
        env:
          GRAPHQL_API_URL: "https:///app.amplication-sandbox.com/graphql"
 # Replace with your GraphQL server endpoint
          AUTH_TOKEN: ${{ secrets.AMPLICATION_API_TOKEN }}                         # Your auth token stored in GitHub Secrets
        run: |
          curl -X POST $GRAPHQL_API_URL \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $AUTH_TOKEN" \
          -d '{"query": "mutation { scaffoldServiceFromTemplate(input: {name: \"value\"}) { fieldToReturn } }"}'
        
